### PR TITLE
MNT: Consolidate build metadata in pyproject.toml

### PR DESCRIPTION
**Pull request by effigies**
My primary goal is actually to remove `cython` from the install-time dependencies, but one thing led to another...

Let me know what you think. I can scale back, if you prefer to keep more of the build metadata as runtime variables in nitime.

Another thing we can consider is getting rid of `version.py` altogether and using [setuptools_scm](https://github.com/pypa/setuptools_scm) to generate the version automatically. Would seem excessive given the rare releases, but it's only a couple lines and would further consolidate metadata for the future.

I also anticipate wanting to make sure there's a 3.12 wheel once numpy starts distributing them.

### CODE REVIEW

**Comment by arokem** [comment]
This all looks good to me. I like setuptools_scm, but just haven't gotten around to adding it here. 

Should we go ahead and merge this first?

**Comment by effigies** [comment]
Done. And wheels are built, showing that versions are correctly determined. (Assuming you like the default version scheme.)

**Comment by arokem** [comment]
Awesome. Thanks! I guess I should cut another micro release once this is in place.

**Comment by effigies** [comment]
I'm definitely not I'm a rush. If it waits until 3.12 is out along with numpy wheels, that'd be fast enough for me.

**Pull request merged**
