### PR TITLE
Use legacy Python syntax

### PR DESCRIPTION
**Pull request by arokem**
After this is released, to be followed up by changes discussed in #174

### CODE REVIEW

**Comment by effigies** [comment]
Any chance of throwing in 2.7, 3.4-3.7 tests on Travis, just to make sure that we're not missing something? This may just be the first error hit by Nipype.

**Comment by arokem** [comment]
OK. Will do.

**Comment by arokem** [comment]
Well, this is a fun little rabbit hole.

**Comment by effigies** [comment]
Sorry to send you down it. Tests passed in arokem#3, so I think you can probably come up for air.

**Comment by arokem** [comment]
Thanks @effigies!

**Pull request merged**
