### PR TITLE
Pin numpy < 2.0 for now.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by larsoner** [comment]
In https://github.com/nipy/nitime/pull/217 I changed the wheels to build against NumPy 2.0 so maybe this isn't needed?

**Comment by larsoner** [comment]
See build reqs

https://github.com/nipy/nitime/blob/696b83424739dd958c0d36f3804c43fc1a9a7271/pyproject.toml#L7

So instead of pinning to < 2 I think if you cut a release things will be okay with 2.0

**Comment by arokem** [comment]
Oh - just realized that! That's awesome. Closing this and I'll try to cut a release from current master instead.

**Comment by arokem** [comment]
Reopening this given #218

**Comment by effigies** [comment]
My previous comment that this seems like a good idea is wrong, on reflection.

If we pin `numpy<2.0.0.dev0` and somebody installs `numpy nitime`, they'll either get `numpy>=2` with an older nitime or the latest nitime with numpy 1.x, but we can't guarantee the second will be what the pip resolver chooses.

I think fixing numpy 2 compatibility is going to be the better path forward, especially if you have @larsoner on the case. :-)

**Comment by arokem** [comment]
Closing, given #221 seems close.

**Pull request closed without merging**
