### PR TITLE
BF: Newer numpy can't deal with the type coercion that comes with inp…

### PR DESCRIPTION
**Pull request by arokem**
…lace div.

Addresses #133?

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I think better to use:
```diff
diff --git a/nitime/tests/test_timeseries.py b/nitime/tests/test_timeseries.py
index c9dd49c..ede7e61 100644
--- a/nitime/tests/test_timeseries.py
+++ b/nitime/tests/test_timeseries.py
@@ -542,7 +542,7 @@ def test_TimeSeries():
     tseries2 = tseries1 * 2
     npt.assert_equal(tseries1.data * 2, tseries2.data)
     npt.assert_equal(tseries1.time, tseries2.time)
-    tseries2 /= 2
+    np.divide(tseries2, 2, out=tseries2)
     npt.assert_equal(tseries1.data, tseries2.data)
     npt.assert_equal(tseries1.time, tseries2.time)
```

I've not tested my snippet, but according to documentation...

**Comment by ignatenkobrain** [comment]
@arokem are you going to merge? ;)

**Comment by gmt710** [comment]
> ```diff
> +    np.divide(tseries2, 2, out=tseries2)
> ```

hello，Thanks for your sharing.But I find may it need to add this:

tseries2 = tseries2.astype(np.float64)
np.divide(tseries2, 2, out=tseries2)

reference:https://docs.scipy.org/doc/numpy/reference/generated/numpy.true_divide.html

**Comment by arokem** [comment]
Hey @gmt710 : would you mind making a new PR with that change?

**Pull request merged**
